name: Tests

on:
  push:
    branches: [ main ]
  pull_request: null

jobs:
  # This workflow contains a single job called "build"
  phpunit:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4' ]
        symfony-validator: [ 3.*, 4.* ]

    name: PHP ${{ matrix.php }} - validator ${{ matrix.symfony-validator }} tests
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

        # use PHP of specific version
      - uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install dependencies
        run: |
          composer require "symfony/validator:${{ matrix.symfony-validator }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-suggest

      - run: vendor/bin/phpunit