name: Test

on:
    pull_request:
        branches: [ main ]

jobs:
    # This workflow contains a single job called "build"
    phpunit:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['7.2', '7.3', '7.4']

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            - name: Run composer install
                  run: composer install --prefer-dist -o

            - name: Execute tests
                  run: vendor/bin/phpunit --colors='always'